### ISSUE TITLE
Lacking support for x86 architecture

### ISSUE THREAD

**Issue by 36805** [Yakov5776/AdvancedRobloxArchival#1]
Error report:
Titlebar: E:\AdvancedRobloxArchival.exe
Content of error: The version of this file is not compatible with the version of Windows you're running. Check your computer's system information to see whether you need an x86 or x64 version of the program, and then contact the software publisher.
Version of Windows: Windows Vista Home Premium 6.0.6002 Service Pack 2 Build 6002 X86 
Processor: Intel Core 2 Duo

**Comment by Yakov5776** [comment]
at the moment this only supports x64, plans for x86 support is planned to release in the next release candidate.

**Comment by Yakov5776** [comment]
[Release Candidate 4.1](https://github.com/Yakov5776/AdvancedRobloxArchival/releases/tag/r4.1) was published, let me know if any other problems are present.
