### ISSUE TITLE
Serious Question

### ISSUE THREAD

**Issue by Robox-Corporation** [Yakov5776/AdvancedRobloxArchival#2]
Can I be assured that this program will not **secretly upload** all of the contents of a folder that contains a client? Or even files inside of the content folder of a client that are not supposed to be there? I have really cool images spread across my computer that I don't want getting leaked.

**Comment by Yakov5776** [comment]
I don't know if this is a joke, but I'll get some stuff clear:
We do not check for anything other than actual binaries and we do check for a valid digital signature before considering them so modified clients of the like are completely out of the picture.
Additionally we do have an experimental "upload clients to public ftp" feature which is in the works although it hasn't been released with any release candidates yet, and it plans to be an opt-in as seen in some of my recent commits.
